#cloud-config
package_upgrade: true
package_update: true

packages:
  - wget
  - git
  - mc
  - ntp
  - python3-pip
  - python3-boto
  - fail2ban
  - awscli
  - glusterfs-server
  - glusterfs-client
  - thin-provisioning-tools

write_files:
  - path: /home/ubuntu/glusterfs.sh
    encoding: b64
    permissions: 0777
    content: ${gluster_sh}

runcmd:
  - /home/ubuntu/glusterfs.sh ${is_master}




